### ISSUE TITLE
Transparency Patcher don't work

### ISSUE THREAD

**Issue by Sndadm** [holly-hacker/DiscordCSS#12]
Hi, Holly,
I was looking for a plugin allowing invisible mode on discord and you are the only one (to my knowledge) to have created this plugin, but when I follow your steps I have a problem to click on "Enable Patch" (https://i.imgur.com/kpMjJBk.png), in your steps you ask to contact you if there is a problem at this level and to send the error code that is written in the console but I don't know how to open it. ^^'

**Comment by HoLLy-HaCKeR** [comment]
This repo isn't for the transparency patch. I don't support it anymore and I know it is broken. If you see anyone trying to use it, please tell them to stop.
